// SPDX-License-Identifier: LGPL-3.0-only

// Tree index generator: `<dir>.ts` as a sibling module with static imports +
// resolver-ready entries. This is how a packaged tree (layer0, a framework's
// layer1, an app shipped as a JSR package) becomes importable when no
// filesystem walk is possible: the index's static imports drag the whole tree
// into the import graph, so `deno install` prefetches it and the module
// system serves it offline thereafter — declaration, not discovery.

import {
  classifyFile,
  dirPatternOf,
  invalidFileError,
  patternOf,
} from "./loader.ts";

const HEADER = "// AUTO-GENERATED by `gen index` — do not edit.\n" +
  "// `gen index --check` enforces drift.\n" +
  "// SPDX-License-Identifier: LGPL-3.0-only\n";

export interface GenIndexOptions {
  /** Import specifier for the `LayerIndexEntry`/`IndexRoot` types.
   * Default: `./loader.ts` (the pathfinder repo). Framework users:
   * `--from @pathfinder/pathfinder`. */
  from?: string;
  /** Drift check: compare against the on-disk file, don't write. */
  check?: boolean;
}

export interface GenIndexResult {
  /** The sibling index path (absolute). */
  file: string;
  /** The full emitted content. */
  content: string;
  /** Entry count (tree files indexed). */
  entries: number;
  /** check mode: content differs from disk (or file missing). */
  drift: boolean;
}

/** Entry fields as emitted (the module ref is joined at emit time). */
type EmittedEntry =
  | {
    kind: "method";
    method: string;
    pattern: string;
    dir: string;
    path: string;
  }
  | { kind: "middleware"; name: string; dir: string; path: string }
  | { kind: "status"; code: number; dir: string; path: string };

/** Generate (or check) the sibling tree index for `<dir>`. */
export async function generateIndex(
  dir: string,
  opts: GenIndexOptions = {},
): Promise<GenIndexResult> {
  const absDir = dir.endsWith("/") ? dir.slice(0, -1) : dir;
  const name = absDir.split("/").pop() ?? "";
  if (name === "" || name === "." || name === "..") {
    throw new Error(
      `[pathfinder] gen index: cannot generate an index for "${dir}" — pass a named tree directory`,
    );
  }
  const file = `${absDir.slice(0, absDir.length - name.length)}${name}.ts`;
  if (file === absDir || file.startsWith(absDir + "/")) {
    throw new Error(
      `[pathfinder] gen index: the index must be a sibling of the tree, never inside it`,
    );
  }

  const entries: EmittedEntry[] = [];
  const imports: string[] = []; // relative paths, emission order

  async function visit(dirRel: string): Promise<void> {
    for await (const item of Deno.readDir(absDir + "/" + dirRel)) {
      const rel = dirRel === "" ? item.name : dirRel + item.name;
      if (item.isDirectory) {
        await visit(rel.endsWith("/") ? rel : rel + "/");
        continue;
      }
      if (!item.isFile) continue;
      const classified = classifyFile(item.name);
      if (classified.kind === "ignored") continue;
      if (classified.kind === "invalid") {
        throw invalidFileError(`${absDir}/${rel}`, rel);
      }
      // Import specifiers URL-encode per segment — `#` in a dirname (the
      // grammar's own param dirs) is a fragment delimiter in a specifier.
      const spec = [name, ...rel.split("/")].map(encodeURIComponent).join("/");
      imports.push(`./${spec}`);
      const path = `${name}/${rel}`;
      if (classified.kind === "method") {
        entries.push({
          kind: "method",
          method: classified.method,
          pattern: patternOf(dirRel),
          dir: dirPatternOf(dirRel),
          path,
        });
      } else if (classified.kind === "middleware") {
        entries.push({
          kind: "middleware",
          name: classified.name,
          dir: dirPatternOf(dirRel),
          path,
        });
      } else {
        entries.push({
          kind: "status",
          code: classified.code,
          dir: dirPatternOf(dirRel),
          path,
        });
      }
    }
  }
  await visit("");

  const from = opts.from ?? "./loader.ts";
  const lines: string[] = [HEADER];
  lines.push(`import type { IndexRoot, LayerIndexEntry } from "${from}";`);
  imports.forEach((rel, i) => lines.push(`import * as m${i} from "${rel}";`));
  lines.push("");
  lines.push("const tree: IndexRoot = {");
  lines.push(`  root: new URL("./", import.meta.url).href,`);
  lines.push("  entries: [");
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    const fields: string[] = [`kind: ${JSON.stringify(e.kind)}`];
    if (e.kind === "method") {
      fields.push(`method: ${JSON.stringify(e.method)}`);
      fields.push(`pattern: ${JSON.stringify(e.pattern)}`);
    }
    if (e.kind === "status") fields.push(`code: ${JSON.stringify(e.code)}`);
    if (e.kind === "middleware") fields.push(`name: ${JSON.stringify(e.name)}`);
    fields.push(`dir: ${JSON.stringify(e.dir)}`);
    fields.push(`path: ${JSON.stringify(e.path)}`);
    fields.push(`mod: m${i}`);
    // Emit fmt-clean: single line when it fits, per-field lines when long
    // (mirrors `deno fmt` object-literal wrapping at 80 columns).
    const single = `    { ${fields.join(", ")} },`;
    if (single.length <= 80) {
      lines.push(single);
    } else {
      lines.push("    {");
      for (const field of fields) lines.push(`      ${field},`);
      lines.push("    },");
    }
  }
  lines.push("  ] satisfies LayerIndexEntry[],");
  lines.push("};");
  lines.push("");
  lines.push("export default tree;");
  lines.push("");
  const content = lines.join("\n");

  let drift = false;
  if (opts.check) {
    let existing: string | null = null;
    try {
      existing = await Deno.readTextFile(file);
    } catch {
      existing = null;
    }
    drift = existing !== content;
  } else {
    await Deno.writeTextFile(file, content);
  }
  return { file, content, entries: entries.length, drift };
}
