// AUTO-GENERATED by `gen index` — do not edit.
// `gen index --check` enforces drift.
// SPDX-License-Identifier: LGPL-3.0-only

import type { IndexRoot, LayerIndexEntry } from "./loader.ts";
import * as m0 from "./layer0/204.ts";
import * as m1 from "./layer0/404.ts";
import * as m2 from "./layer0/405.ts";
import * as m3 from "./layer0/413.ts";
import * as m4 from "./layer0/500.ts";
import * as m5 from "./layer0/_status/10-loopback.ts";
import * as m6 from "./layer0/_status/get.ts";
import * as m7 from "./layer0/_status/health/get.ts";

const tree: IndexRoot = {
  root: new URL("./", import.meta.url).href,
  entries: [
    { kind: "status", code: 204, dir: "", path: "layer0/204.ts", mod: m0 },
    { kind: "status", code: 404, dir: "", path: "layer0/404.ts", mod: m1 },
    { kind: "status", code: 405, dir: "", path: "layer0/405.ts", mod: m2 },
    { kind: "status", code: 413, dir: "", path: "layer0/413.ts", mod: m3 },
    { kind: "status", code: 500, dir: "", path: "layer0/500.ts", mod: m4 },
    {
      kind: "middleware",
      name: "10-loopback",
      dir: "/_status",
      path: "layer0/_status/10-loopback.ts",
      mod: m5,
    },
    {
      kind: "method",
      method: "GET",
      pattern: "/_status",
      dir: "/_status",
      path: "layer0/_status/get.ts",
      mod: m6,
    },
    {
      kind: "method",
      method: "GET",
      pattern: "/_status/health",
      dir: "/_status/health",
      path: "layer0/_status/health/get.ts",
      mod: m7,
    },
  ] satisfies LayerIndexEntry[],
};

export default tree;
