// SPDX-License-Identifier: LGPL-3.0-only

// Generated route types (#41-params; ledger §10.3): the loader's walker +
// grammar.ts as type emitter. Matryoshka architecture — per-directory
// interfaces extending their parents, so params accumulate down dynamic
// segments exactly as cascade/seats/overlays scope. Binding: per-dir
// generated `$types.d.ts`, SvelteKit-style explicit import. Drift gate:
// `gen --check` in CI.
//
// Paths are built as plain strings — `new URL()` with a `#` dirname would
// treat it as a fragment (the toFileUrl lesson).

import type { Chunk } from "./grammar.ts";
import { parsePattern } from "./grammar.ts";

const HEADER =
  "// AUTO-GENERATED by `deno task gen` — do not edit. `deno task gen:check` enforces.\n// SPDX-License-Identifier: LGPL-3.0-only\n// deno-lint-ignore-file no-empty-interface\n\n";

export interface GenResult {
  files: string[]; // written (or compared in --check)
  drift: string[]; // files that differ (only in check mode)
}

interface DirNode {
  /** Relative dir path, "" = root, trailing slash included for children. */
  rel: string;
  children: Map<string, DirNode>;
  /** Own params: name → TS type. */
  params: Map<string, string>;
}

function newDir(rel: string): DirNode {
  return { rel, children: new Map(), params: new Map() };
}

/** Dirname → param type per the registry: `#x` → string, `#(num)x` → number,
 * `#(int)x` → bigint, `#...x` → string (rests are untyped). */
export function dirParams(dirname: string): Map<string, string> {
  const params = new Map<string, string>();
  if (!dirname.startsWith("#")) return params;
  let chunks: Chunk[];
  try {
    // The dirname as a single dynamic segment; the grammar does the rest.
    chunks = parsePattern(dirname);
  } catch {
    return params; // not a param dir (invalid name — build error elsewhere)
  }
  for (const chunk of chunks) {
    if (chunk.kind !== "dynamic") continue;
    const tsType = chunk.type === "int"
      ? "bigint"
      : chunk.type === "num"
      ? "number"
      : "string";
    params.set(chunk.name, tsType);
  }
  return params;
}

async function rootDirPath(root: string | URL): Promise<string> {
  const url = root instanceof URL ? root : toFileUrlLike(root);
  const path = decodeURIComponent(url.pathname);
  return path.endsWith("/") ? path : path + "/";
}

function toFileUrlLike(path: string): URL {
  // Absolute fs path → file URL, preserving characters `new URL(path)` would
  // eat (e.g. `#`).
  const resolved = path.startsWith("/") ? path : `${Deno.cwd()}/${path}`;
  return new URL("file://" + encodePath(resolved));
}

function encodePath(path: string): string {
  return path.split("/").map(encodeURIComponent).join("/");
}

async function buildTree(root: string | URL): Promise<string> {
  return await rootDirPath(root);
}

function render(node: DirNode, isRoot: boolean): string {
  const lines: string[] = [];
  if (isRoot) {
    // Honest-union baseline (§10.2): post-coercion, Record<string,string>
    // would be a lie.
    lines.push(
      "export interface Params extends Record<string, string | number | bigint> {}",
    );
  } else {
    lines.push(`import type { Params as ParentParams } from "../$types.d.ts";`);
    if (node.params.size === 0) {
      lines.push("export interface Params extends ParentParams {}");
    } else {
      lines.push("export interface Params extends ParentParams {");
      for (
        const [name, tsType] of [...node.params.entries()].sort(([a], [b]) =>
          a.localeCompare(b)
        )
      ) {
        lines.push(`  ${JSON.stringify(name)}: ${tsType};`);
      }
      lines.push("}");
    }
  }
  return HEADER + lines.join("\n") + "\n";
}

export async function generateTypes(
  roots: (string | URL)[],
  opts: { check?: boolean } = {},
): Promise<GenResult> {
  const files: string[] = [];
  const drift: string[] = [];
  for (const root of roots) {
    const basePath = await buildTree(root);
    async function emit(rel: string, node: DirNode): Promise<void> {
      const content = render(node, rel === "");
      const path = basePath + rel + "$types.d.ts";
      files.push(path);
      if (opts.check) {
        let existing: string | null = null;
        try {
          existing = await Deno.readTextFile(path);
        } catch {
          existing = null;
        }
        if (existing !== content) drift.push(path);
      } else {
        await Deno.writeTextFile(path, content);
      }
      for (const child of node.children.values()) await emit(child.rel, child);
    }
    const tree = newDir("");
    async function visit(rel: string, node: DirNode): Promise<void> {
      const dirPath = basePath + rel;
      let items: Deno.DirEntry[] = [];
      try {
        items = [];
        for await (const item of Deno.readDir(dirPath)) items.push(item);
      } catch {
        return;
      }
      for (const item of items) {
        if (!item.isDirectory) continue;
        const childRel = rel + item.name + "/";
        const child = newDir(childRel);
        child.params = dirParams(item.name);
        node.children.set(item.name, child);
        await visit(childRel, child);
      }
    }
    await visit("", tree);
    await emit("", tree);
  }
  return { files, drift };
}
